name: Flexible Multi-Language SonarCloud Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build and Test Projects
        run: |
          for dir in $(find . -maxdepth 5 -type d); do
            if [ -f "$dir/pom.xml" ]; then
              echo "Building Java project in $dir"
              (cd "$dir" && mvn clean install)
            elif [ -f "$dir/requirements.txt" ]; then
              echo "Testing Python project in $dir"
              (cd "$dir" && \
               pip install -r requirements.txt)
            else
              echo "Skipping $dir — no build config found."
            fi
          done

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
