

on:
  push:
    branches:
      - 'python_*'  # Only runs for branches that start from python
  workflow_dispatch:  # Optional: allows manual triggering

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install SonarScanner CLI
        run: |
          npm install -g sonar-scanner

      - name: Run SonarCloud scan in each Python subfolder
        run: |
          echo " Finding sonar-project.properties for Python folders..."
          for dir in $(find LLM_experiments/python -type f -name sonar-project.properties -exec dirname {} \;); do
            echo " Installing dependencies in $dir"
            if [ -f "$dir/requirements.txt" ]; then
              pip install -r "$dir/requirements.txt" || echo " Skipped broken requirements in $dir"
            fi

            echo " Running sonar-scanner in $dir"
            (cd "$dir" && sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }}) || echo " Scan failed in $dir"
          done
